name: Build plugins in Release folder

on:
  workflow_dispatch:  

jobs:
  build-windows:
    
    runs-on: windows-latest

    permissions:
      contents: write
    
    defaults:
      run:
        shell: msys2 {0}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        update: true
        install: >-
          git
        pacboy: >-
          gcc:p
          cmake:p
          ninja:p 
          gtk3:p
          glew:p 
    
    - name: Build the Project
      run: |
          mkdir -p build
          cd build
          cmake -GNinja -DOUTPUT_DIR="../release/Aircraft/Extra Aircraft/NK_FPVSurfwing/plugins/INAV-X-Plane-HITL/64" ..
          ninja

    - name: Commit win.xpl
      shell: powershell  
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add "release/Aircraft/Extra Aircraft/NK_FPVSurfwing/plugins/INAV-X-Plane-HITL/64/win.xpl"
        git commit -m "Action - Update win.xpl" -or echo "No changes to commit"
        git pull origin main --rebase
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-linux:
    
    runs-on: ubuntu-latest

    permissions:
      contents: write    

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get -y install -y ninja-build cmake gcc g++ libglew-dev libgl-dev libglu1-mesa-dev libalut-dev libgtk-3-dev pkg-config

    - name: Build the project
      run: |
        mkdir build
        cd build
        cmake -GNinja -DOUTPUT_DIR="../release/Aircraft/Extra Aircraft/NK_FPVSurfwing/plugins/INAV-X-Plane-HITL/64" ..
        ninja

    - name: Commit lin.xpl
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add "release/Aircraft/Extra Aircraft/NK_FPVSurfwing/plugins/INAV-X-Plane-HITL/64/lin.xpl"
        git commit -m "Action - Update lin.xpl" || echo "No changes to commit"
        git pull origin main --rebase
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-mac:
    runs-on: macos-13

    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install Dependencies
      run: brew install ninja cmake gtk+3 openal-soft glew
 
    - name: Build the project
      run: |
        mkdir build
        cd build
        cmake -GNinja -DOUTPUT_DIR="../release/Aircraft/Extra Aircraft/NK_FPVSurfwing/plugins/INAV-X-Plane-HITL/64" ..
        ninja

    - name: Commit mac.xpl
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add "release/Aircraft/Extra Aircraft/NK_FPVSurfwing/plugins/INAV-X-Plane-HITL/64/mac.xpl"
        git commit -m "Action - Update mac.xpl" || echo "No changes to commit"
        git pull origin main --rebase
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  create_aircraft_zip:
    runs-on: ubuntu-latest
    needs: [build-windows, build-linux, build-mac]  
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Upload Aircraft.zip
        uses: actions/upload-artifact@v4
        with:
          name: Aircraft
          path: release/**  